### ISSUE TITLE
Aborted: Cannot read properties of undefined (reading '_clientVersion')

### ISSUE THREAD

**Issue by weiihann** [eth-infinitism/bundler#78]
I'm running my own Geth node on Goerli with the following command:

```
./go-ethereum/build/bin/geth --goerli --datadir /server2/weihan/ethereum/execution/datadir  --http --http.api personal,eth,net,web3,debug --http.vhosts '*, localhost, host.docker.internal' --http.addr "0.0.0.0" --allow-insecure-unlock --rpc.allow-unprotected-txs --authrpc.jwtsecret=/opt/jwtsecret
```

I tried to run a bundler on Goerli using the following command:
```
yarn run bundler --network goerli --mnemonic mnemonic.txt
```

but got the following error:
```
command-line arguments:  {
  config: './localconfig/bundler.config.json',
  auto: false,
  network: 'goerli',
  mnemonic: 'mnemonic.txt'
}
Merged configuration: {"port":"3000","entryPoint":"0x0576a174D229E3cFA37253523E645A78A0C91B57","unsafe":false,"conditionalRpc":false,"gasFactor":"1","network":"goerli","beneficiary":"0xd21934eD8eAf27a67f0A70042Af50A1D6d195E81","minBalance":"1","mnemonic":"mnemonic.txt","maxBundleGas":5000000,"minStake":"1","minUnstakeDelay":0,"autoBundleInterval":3,"autoBundleMempoolSize":10}
Aborted: Cannot read properties of undefined (reading '_clientVersion')
```

Any idea how to tackle this issue?

**Comment by ebaizel** [comment]
I am getting the same error. It looks like the problem is that `provider.send` is not a valid function. However, it looks like it is a valid function of [JsonRpcProvider](provider.send is not a function).

It seems like the problem is that the Provider that gets [instantiated](https://github.com/eth-infinitism/bundler/blob/main/packages/bundler/src/Config.ts#L38) is an instance of the Provider class which does not have a `send` function.

To test it, I changed that line to `: new ethers.providers.JsonRpcProvider("https://eth-goerli.g.alchemy.com/v2/mykey");` and it is able to connect.
